name: Trigger Jenkins Build on Commit

on:
  push:
    branches:
      - main
    paths:
      - f1.txt

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        run: |
           curl -X POST "${{ secrets.JENKINS_URL }}/job/beta-node-app/build" --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" || true
